### ISSUE TITLE
Cannot install by following the CONTRIBUTING instructions

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-specification#1192]
I may need someone to check whether this is a case of [PIKACI](https://www.urbandictionary.com/define.php?term=pibkac) and I 
am the only one who cannot install the bidsschema tools.

Trying to pretty much follow the CONTRIBUTING.md

```bash
conda create --name bids-spec
conda activate bids-spec
conda install pip  # not in the contributing but ensure that pip will install package in the conda env
pip install -U pip
pip install -r requirements.txt
pip install -e ./tools/schemacode # FYI this is redundant with above as this is already in the requrirements.txt but the contributing asks for it.
```

Can someone try to reproduce this?

---

So basically:

python --version
Python 3.10.4

pip list
Package    Version
---------- ---------
certifi    2022.6.15
pip        22.2.2
setuptools 63.4.2
wheel      0.37.1

I get the this error.

<details><summary> <b>Error</b> </font> </summary><br>

```bash 
pip install -r requirements.txt
Processing ./tools/schemacode
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [42 lines of output]
      /tmp/pip-build-env-7zh486b1/overlay/lib/python3.10/site-packages/setuptools/config/expand.py:142: UserWarning: File '/home/remi/github/BIDS-specification/tools/schemacode/bidsschematools/data/schema/SCHEMA_VERSION' cannot be found
        warnings.warn(f"File {path!r} cannot be found")
      Traceback (most recent call last):
        File "/tmp/pip-build-env-7zh486b1/overlay/lib/python3.10/site-packages/setuptools/config/setupcfg.py", line 592, in _parse_version
          Version(version)
        File "/tmp/pip-build-env-7zh486b1/overlay/lib/python3.10/site-packages/setuptools/_vendor/packaging/version.py", line 266, in __init__
          raise InvalidVersion(f"Invalid version: '{version}'")
      setuptools.extern.packaging.version.InvalidVersion: Invalid version: ''
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/home/remi/miniconda3/envs/bids-spec/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/remi/miniconda3/envs/bids-spec/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/remi/miniconda3/envs/bids-spec/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-7zh486b1/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/tmp/pip-build-env-7zh486b1/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-7zh486b1/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(code, locals())
        File "<string>", line 1, in <module>
        File "/tmp/pip-build-env-7zh486b1/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-7zh486b1/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 159, in setup
          dist.parse_config_files()
        File "/tmp/pip-build-env-7zh486b1/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 864, in parse_config_files
          setupcfg.parse_configuration(
        File "/tmp/pip-build-env-7zh486b1/overlay/lib/python3.10/site-packages/setuptools/config/setupcfg.py", line 174, in parse_configuration
          meta.parse()
        File "/tmp/pip-build-env-7zh486b1/overlay/lib/python3.10/site-packages/setuptools/config/setupcfg.py", line 496, in parse
          section_parser_method(section_options)
        File "/tmp/pip-build-env-7zh486b1/overlay/lib/python3.10/site-packages/setuptools/config/setupcfg.py", line 470, in parse_section
          self[name] = value
        File "/tmp/pip-build-env-7zh486b1/overlay/lib/python3.10/site-packages/setuptools/config/setupcfg.py", line 278, in __setitem__
          value = parser(value)
        File "/tmp/pip-build-env-7zh486b1/overlay/lib/python3.10/site-packages/setuptools/config/setupcfg.py", line 598, in _parse_version
          raise DistutilsOptionError(tmpl.format(**locals()))
      distutils.errors.DistutilsOptionError: Version loaded from file:bidsschematools/data/schema/SCHEMA_VERSION does not comply with PEP 440:
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

</details>

**Comment by sappelhoff** [comment]
`pip install -e ./tools/schemacode # FYI this is redundant with above as this is already in the requrirements.txt but the contributing asks for it.`

this is an editable install so that changes in the schema are immediately reflected in the user python env -- otherwise they'd have to re-install the schemacode after each change. Perhaps there is a way to add an "editable" flag to requirements.txt?

https://github.com/bids-standard/bids-specification/blob/c24835c4a865043ba1b6a38af52b717c0c742a2b/requirements.txt#L7

**Comment by sappelhoff** [comment]
The issue seems to be related to changes in how the version in the schema is represented? I think @TheChymera has touched that code recently. Can you shed some light perhaps?

**Comment by effigies** [comment]
> this is an editable install so that changes in the schema are immediately reflected in the user python env -- otherwise they'd have to re-install the schemacode after each change. Perhaps there is a way to add an "editable" flag to requirements.txt?

```diff
-tools/schemacode/
+-e tools/schemacode/
```

**Comment by Remi-Gau** [comment]
hum... a "git xkcd" seems to to have "fixed" this. 

# :shrug:
